--- 
title: "Open Collaboration Guide"
author: ["Daniel Antal"]
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
output: 
  bookdown::gitbook: default
  bookdown::pdf_book:
    language: english
    template: null
    toc: true
    tof: true
    includes:
      keep_tex: true
  bookdown::word_document2:
    toc: false
    reference_docx: templates/collab-template.docx
    language: english
classoption: openany, a4paper, oneside
lang: en
papersize: a4
fontsize: "fontsize=13pt"
linestretch: 1.1
urlcolor: blue
linkcolor: blue
geometry: "left=3cm, right=3cm, top=2.5cm, bottom=2.5cm"
bibliography: [book.bib, packages.bib, antal.bib, ccipolicy.bib, datascience.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a collaboration guide for Reprex open-source projects."
---

# Welcome {-}

`I didn't have time to write a short letter, so I wrote a long one instead.` — *Mark Twain* 

For collaborators who do not write code, the general [Introduction](#intro) contains  a [Simple Introduction](#simple-intro) focusing on documentation tools only. Contributors with no coding experience and ambition will likely work with [data curation](#data-curation) and [documentation,  publications](#documentation) which is equally important to developing code. You must be familiar with our developers [naming conventions](#naming-conventions), because we automate research: their programs create data tables, visualizations, maps, blogposts, even books following this vocabulary.

Most of this long-form documentation is intended for collaborators who write code to [acquire data](#acquisition), [store data](#data-storage), create applications such a [statistics](#statistical-software), or [machine learning applications](#machine-learning), and who help us [publish data](#data-release).

Open collaboration is an agile project management method that breaks up the tasks to small, independent, decentralized acts that can be performed by individuals or research groups.  It requires a solid shared knowledge base and a very high quality documentation. This collaboration guide serves two goals: to practice this documentation workflow, and to create a continuously improved documentation for our collaboration methods and practices.

We [pledge](#pledge) to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community. We ask you to contribute to the growth of our open collaboration, and we would like to contribute to your growth. We would love to work with your favorite [data](#data-curation), add your inspiring reading and listening [recommendations](#inspiration) to this guide and cite your [work](#bibliography) throughout or publications.

You can edit yourselft this guide on [github](https://github.com/dataobservatory-eu/collaboration_guide/). The html, [epub](https://open-collaboration-guide.dataobservatory.eu/reprex_collaboration_guide.docx), [docx](https://open-collaboration-guide.dataobservatory.eu/reprex_collaboration_guide.docx) and pdf versions can be found on [open-collaboration-guide.dataobservatory.eu](https://open-collaboration-guide.dataobservatory.eu/). The pdf is not working.

```{r crate-bibliography, include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'regions', 'retroharmonize', 'iotables'), 'packages.bib')
```
